
server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baozhuming/spring-cloud-learning/
          search-paths: config/repo
          username: baozhuming
          password: a05140212+