zuul:
  routes:
    baid3:
#      serviceId: hello-service
      url: http://www.baidu.com/
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer
#      sensitiveHeaders:
    api-b:
      path: /api-b/**
      serviceId: config-server
      sensitiveHeaders:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
  ignored-services: '*'