server:
  port: 8762
spring:
  application:
    name: eureka-peer2
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
