server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    #register-with-eureka: false
    #fetch-registry: false
