server:
  port: 8761
spring:
  application:
    name: eureka-peer1
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
